.github/workflows/pr-preview-artifact.yml, README.md
Testing creation of PR site for previewing
=> Add a change to test PR preview site

basic_software_and_package_installation/environment_modules/index.rst, basic_software_and_package_installation/index.rst, basic_software_and_package_installation/other_software_installs/index.rst, basic_software_and_package_installation/packages_in_julia_python_r/index.rst
Another set of section sub-headings
=> Adding software headings

.gitignore, docs/recipes/mujoco.md
Adding "How To" recipe for installing and using Mujoco on both Engaging and SuperCloud
=> Adding mujoco recipe

docs/recipes/h100_getting_started.md
Start place holder for H100 testing docs
=> H100 testing notes 

docs/recipes/gromacs.md, mkdocs.yml, requirements.txt
https://mit-orcd.github.io/orcd-docs-previews/PR/PR19/
=> Add open in new tab

docs/data-security.md
Adding text from https://orcd.mit.edu/resources to the Data Security page
=> adding text to data security page

docs/filesystems-file-transfer/filesystems.md, mkdocs.yml
Adding page to list out the different filesystems on each system.
=> Adding Filesystems Page

docs/acknowledgements.md, docs/code-of-conduct.md, docs/getting-started.md, mkdocs.yml
Initial Getting Started page based on the SuperCloud one: https://supercloud.mit.edu/getting-started.
=> Getting Started Page

docs/data-security.md
https://mit-orcd.github.io/orcd-docs-previews/PR/PR34
=> Add support staff access wording

docs/orcd-systems.md
Updating weekly login node restarts to 7am
=> Update maintenance schedule

docs/getting-help.md
Adding the new Tuesday office hours session to the Getting Help page.
=> Adding new OH session

docs/software/modules.md, docs/software/overview.md, docs/software/python.md, mkdocs.yml
Adding a section on Software. Here is a rough planned outline:
- About the software stack (core, community, deprecated)
- “Steps” to take (check modules, install for yourself, ask for help)
- Checking what modules exist
- Loading modules
- Listing loaded modules
- Removing/purging modules
- Writing your own modules (writing the files, module use)
- Modules
- Pip
- Environments (venv and conda)
See full Software Section checklist in #44
=> WIP: Adding Software Section

docs/filesystems-file-transfer/transferring-files.md
Adding a brief Globus section listing the current endpoints. This will be replaced in the near future with the new Globus setup, perhaps with its own more detailed page.
=> Adding Globus section

docs/recipes/mpi.md, docs/software/modules.md, docs/software/python.md
Updated module paths for reorganized community modules.
=> update module paths

docs/software/python.md
No need to run a "module use" command anymore
=> Update miniforge instructions

docs/recipes/orca.md
https://mit-orcd.github.io/orcd-docs-previews/PR/PR87/recipes/orca
=> added section on MPI

docs/recipes/af3.md
Saving .sif image globally because the image pulled from Dockerhub no longer works
=> adding path to .sif

docs/running-jobs/available-resources.md, mkdocs.yml
https://mit-orcd.github.io/orcd-docs-previews/PR/PR108/running-jobs/available-resources/
=> Adding tables on public partitions

docs/filesystems-file-transfer/project-filesystems.md
Update table with storage options, adding "Coming Soon" to compute tier storage.
=> Update Project Filesystems Table

docs/faqs.md, docs/recipes/vscode.md
https://mit-orcd.github.io/orcd-docs-previews/PR/PR139/faqs
=> adding preemption, duo, vs code FAQs

docs/glossary.md, mkdocs.yml
https://mit-orcd.github.io/orcd-docs-previews/PR/PR140/glossary
=> adding glossary page

docs/recipes/X11.md
Clarified instructions for using X11 on Mac and Linux.
=> Update X11.md with clearer terminal instructions
